name: Build

on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false

jobs:

  build_window64:
    name: Windows64
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build
      if: ${{inputs.debug != 'true'}}
      run: |
        echo ${{inputs.debug}}
        .\make_win64.bat
    - name: Build
      if: ${{inputs.debug == 'true'}}
      run: |
        .\make_win64.bat Debug
    - uses: actions/upload-artifact@v2
      with:
        name: pixqjs_bin
        path: qjs/**/*
        
  build_window32:
    name: Windows32
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        .\make_win32.bat
    - uses: actions/upload-artifact@v2
      with:
        name: pixqjs_bin
        path: qjs/**/*
        
  build_ios:
    name: iOS
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Use Xcode 12.0 to use SDK 10.15
      run: sudo xcode-select -switch "/Applications/Xcode_12.app"
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./make_ios.sh
    - uses: actions/upload-artifact@v2
      with:
        name: pixqjs_bin
        path: qjs/**/*
        
  build_macos:
    name: macOS
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Use Xcode 12.0 to use SDK 10.15
      run: sudo xcode-select -switch "/Applications/Xcode_12.app"
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        sh ./make_osx.sh
    - uses: actions/upload-artifact@v2
      with:
        name: pixqjs_bin
        path: qjs/**/*
        
  build_android:
    name: Android
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install NDK
      run: |
        cd ~
        wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
        sudo apt install unzip -y
        unzip -q NDK
        export ANDROID_NDK=~/android-ndk-r21b
    - name: Run build script
      run: |
        cd $GITHUB_WORKSPACE
        ./make_android.sh
    - uses: actions/upload-artifact@v2
      with:
        name: pixqjs_bin
        path: qjs/**/*
        

